# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: transport_management_db
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./transport-management-service   # directorio donde se encuentra el Dockerfile del backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./transport-management-front  # directorio donde se encuentra el Dockerfile del frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
